-- 1. Create and use your database
CREATE DATABASE IF NOT EXISTS mydiet_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mydiet_db;

-- 2. Users table 
CREATE TABLE `users` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `uid` VARCHAR(100) NOT NULL UNIQUE COMMENT 'UID generated by frontend or login token',
  `username` VARCHAR(50) NOT NULL COMMENT 'User nickname',
  `avatar_url` VARCHAR(255) COMMENT 'Real avatar image URL',
  `avatar_gradient` VARCHAR(50) COMMENT 'Gradient background from frontend',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Posts table
CREATE TABLE `posts` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL COMMENT 'Author ID',
  `title` VARCHAR(255) NOT NULL COMMENT 'Post title',
  `content` TEXT COMMENT 'Post content',
  `image_url` LONGTEXT COMMENT 'Image URL or Base64', 
  `likes` INT DEFAULT 0 COMMENT 'Number of likes',     
  `tags` JSON COMMENT 'Array of tags, e.g., ["#30DayFatLoss", "#Healthy"]',
  `nutrition` JSON COMMENT 'Nutrition data object',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Comments table 
CREATE TABLE `comments` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `post_id` BIGINT NOT NULL COMMENT 'Which post this belongs to',
  `user_id` BIGINT NOT NULL COMMENT 'Commenter ID',
  `parent_id` BIGINT NULL COMMENT 'Parent comment ID if it is a reply; NULL if it is a direct comment on the post',
  `content` TEXT NOT NULL COMMENT 'Comment text',
  `likes` INT DEFAULT 0 COMMENT 'Number of likes',     
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`post_id`) REFERENCES `posts`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`parent_id`) REFERENCES `comments`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Post_Likes table
CREATE TABLE `post_likes` (
  `post_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`post_id`, `user_id`), -- Composite primary key ensures a user can only like a post once
  FOREIGN KEY (`post_id`) REFERENCES `posts`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. User_Follows table
CREATE TABLE `user_follows` (
  `follower_id` BIGINT NOT NULL COMMENT 'Follower ID (Fan)',
  `following_id` BIGINT NOT NULL COMMENT 'Following ID (Blogger/Creator)',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`follower_id`, `following_id`),
  FOREIGN KEY (`follower_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`following_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;